// SPDX-FileCopyrightText: 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
//
// SPDX-License-Identifier: MIT

//! Direct unit tests for `IndexingTextSink` / `NodeSpan` (spec 0110 §3).
//!
//! `IndexingTextSink` has no consumer within spec 0110's own scope, so its
//! correctness is established here rather than deferred to a downstream
//! consumer crate.

use std::ops::Range;
use std::path::{Path, PathBuf};

use prototext_core::serialize::render_text::{
    decode_and_render_indexed, DecodeRenderOpts, NodeSpan,
};
use prototext_core::{clear_any_loader, parse_schema, schema_from_pool, set_any_loader};

// ── Fixture helpers (duplicated per prototext/tests/*.rs convention — no
// shared common.rs in this crate; see roundtrip.rs for the same pattern) ──────

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

fn schema_path(schema_rel: &str) -> PathBuf {
    // .pb schemas are generated by build.rs into OUT_DIR (not committed to git).
    let generated = [
        "descriptor.pb",
        "knife.pb",
        "enum_collision.pb",
        "message_set.pb",
    ];
    if let Some(name) = generated
        .iter()
        .find(|&&n| schema_rel == format!("fixtures/schemas/{n}"))
    {
        return PathBuf::from(env!("OUT_DIR")).join(name);
    }
    repo_root().join(schema_rel)
}

fn load_schema(schema_rel: &str, message: &str) -> prototext_core::ParsedSchema {
    let path = schema_path(schema_rel);
    let bytes = std::fs::read(&path)
        .unwrap_or_else(|e| panic!("cannot read schema {}: {e}", path.display()));
    parse_schema(&bytes, message)
        .unwrap_or_else(|e| panic!("cannot parse schema {schema_rel}:{message}: {e}"))
}

fn message_set_schema(message: &str) -> prototext_core::ParsedSchema {
    load_schema(
        "fixtures/schemas/message_set.pb",
        &format!("test_ms.{message}"),
    )
}

fn knife_schema(message: &str) -> prototext_core::ParsedSchema {
    load_schema("fixtures/schemas/knife.pb", message)
}

/// Install an `ANY_LOADER` backed by `schema`'s pool for the duration of
/// `f` — required for any `google.protobuf.Any` expansion (spec 0089/0106).
fn with_any_loader<T>(schema: &prototext_core::ParsedSchema, f: impl FnOnce() -> T) -> T {
    let pool = schema.pool().clone();
    set_any_loader(Box::new(move |fqdn: &str| {
        pool.get_message_by_name(fqdn).map(std::sync::Arc::new)
    }));
    let result = f();
    clear_any_loader();
    result
}

// Wire bytes for Container { name: "test", extensions: TestMessageSet { ... } }
// where extensions has:
//   Item { type_id: 100, message: ExtPayloadA { label: "hello", value: 42 } }
//   Item { type_id: 200, message: ExtPayloadB { flag: true, count: 99 } }
// (byte layout derived exactly as in roundtrip.rs's `CONTAINER_WIRE`).
const CONTAINER_WIRE: &[u8] =
    &hex_literal::<34>("0a0474657374121a0b10641a090a0568656c6c6f102a0c0b10c8011a04080110630c");

const fn hex_literal<const N: usize>(s: &str) -> [u8; N] {
    let b = s.as_bytes();
    let mut out = [0u8; N];
    let mut i = 0;
    while i < N {
        let hi = nibble(b[i * 2]);
        let lo = nibble(b[i * 2 + 1]);
        out[i] = (hi << 4) | lo;
        i += 1;
    }
    out
}

const fn nibble(b: u8) -> u8 {
    match b {
        b'0'..=b'9' => b - b'0',
        b'a'..=b'f' => b - b'a' + 10,
        b'A'..=b'F' => b - b'A' + 10,
        _ => panic!("invalid hex digit"),
    }
}

/// Hand-build `google.protobuf.Any` (type_url=1 string, value=2 bytes) +
/// `acme.Payload` (label=1 string) + `acme.Container` (payload=1, typed
/// `.google.protobuf.Any`), seeded from `descriptor.pb` in `OUT_DIR`
/// (mirrors roundtrip.rs's `any_schema`).
fn any_schema() -> prototext_core::ParsedSchema {
    use prost::Message as _;
    use prost_reflect::DescriptorPool;
    use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorProto};

    let descriptor_pb =
        std::fs::read(std::path::PathBuf::from(env!("OUT_DIR")).join("descriptor.pb"))
            .expect("cannot read descriptor.pb from OUT_DIR");
    let mut pool =
        DescriptorPool::decode(descriptor_pb.as_slice()).expect("cannot decode descriptor.pb");

    let any_msg = DescriptorProto {
        name: Some("Any".into()),
        field: vec![
            FieldDescriptorProto {
                name: Some("type_url".into()),
                number: Some(1),
                r#type: Some(9), // TYPE_STRING
                label: Some(1),  // LABEL_OPTIONAL
                ..Default::default()
            },
            FieldDescriptorProto {
                name: Some("value".into()),
                number: Some(2),
                r#type: Some(12), // TYPE_BYTES
                label: Some(1),   // LABEL_OPTIONAL
                ..Default::default()
            },
        ],
        ..Default::default()
    };
    let any_file = FileDescriptorProto {
        name: Some("google/protobuf/any.proto".into()),
        syntax: Some("proto3".into()),
        package: Some("google.protobuf".into()),
        message_type: vec![any_msg],
        ..Default::default()
    };
    let mut any_file_bytes = Vec::new();
    any_file.encode(&mut any_file_bytes).unwrap();
    pool.decode_file_descriptor_proto(any_file_bytes.as_slice())
        .expect("cannot add google/protobuf/any.proto to pool");

    let payload_msg = DescriptorProto {
        name: Some("Payload".into()),
        field: vec![FieldDescriptorProto {
            name: Some("label".into()),
            number: Some(1),
            r#type: Some(9), // TYPE_STRING
            label: Some(1),  // LABEL_OPTIONAL
            ..Default::default()
        }],
        ..Default::default()
    };

    let container_msg = DescriptorProto {
        name: Some("Container".into()),
        field: vec![FieldDescriptorProto {
            name: Some("payload".into()),
            number: Some(1),
            r#type: Some(11), // TYPE_MESSAGE
            label: Some(1),   // LABEL_OPTIONAL
            type_name: Some(".google.protobuf.Any".into()),
            ..Default::default()
        }],
        ..Default::default()
    };

    let acme_file = FileDescriptorProto {
        name: Some("acme.proto".into()),
        syntax: Some("proto2".into()),
        package: Some("acme".into()),
        dependency: vec!["google/protobuf/any.proto".into()],
        message_type: vec![payload_msg, container_msg],
        ..Default::default()
    };
    let mut acme_bytes = Vec::new();
    acme_file.encode(&mut acme_bytes).unwrap();
    pool.decode_file_descriptor_proto(acme_bytes.as_slice())
        .expect("cannot add acme.proto to pool");

    schema_from_pool(pool, "acme.Container").expect("cannot build any_schema")
}

/// Wire bytes for:
///   Container { payload: Any { type_url: "type.googleapis.com/acme.Payload"
///                              value: Payload { label: "hello" } } }
fn any_wire_bytes() -> Vec<u8> {
    let label = b"hello";
    let mut payload_bytes = vec![0x0a, label.len() as u8];
    payload_bytes.extend_from_slice(label);

    let type_url = b"type.googleapis.com/acme.Payload";

    let mut any_bytes = Vec::new();
    any_bytes.push(0x0a); // field 1, LEN
    any_bytes.push(type_url.len() as u8);
    any_bytes.extend_from_slice(type_url);
    any_bytes.push(0x12); // field 2, LEN
    any_bytes.push(payload_bytes.len() as u8);
    any_bytes.extend_from_slice(&payload_bytes);

    let mut wire = vec![0x0a, any_bytes.len() as u8];
    wire.extend_from_slice(&any_bytes);
    wire
}

// ── Span-assertion helpers ─────────────────────────────────────────────────

/// `outer` fully contains `inner` (both endpoints inclusive of `outer`'s
/// own bounds) — the containment relation `NodeSpan::raw_range`/`text_range`
/// must satisfy between a parent and any of its descendants (spec 0110 §3,
/// "Nesting invariant").
fn contains(outer: &Range<usize>, inner: &Range<usize>) -> bool {
    outer.start <= inner.start && inner.end <= outer.end
}

fn assert_contains(
    outer_label: &str,
    outer: &Range<usize>,
    inner_label: &str,
    inner: &Range<usize>,
) {
    assert!(
        contains(outer, inner),
        "{outer_label} range {outer:?} does not contain {inner_label} range {inner:?}"
    );
}

/// The rendered text's line at line-number `idx` (0-indexed count of `\n`
/// bytes written before it — matches `NodeSpan::text_range`'s convention).
fn line_at(text: &str, idx: usize) -> &str {
    text.split('\n')
        .nth(idx)
        .unwrap_or_else(|| panic!("no line {idx} in text: {text:?}"))
}

// ── Nesting invariant ──────────────────────────────────────────────────────

#[test]
fn nesting_invariant_text_and_raw_ranges_are_contained() {
    let schema = message_set_schema("Container");
    let (text, spans) = decode_and_render_indexed(
        CONTAINER_WIRE,
        schema.root_descriptor().as_ref(),
        DecodeRenderOpts {
            annotations: true,
            emit_header: true,
            ..Default::default()
        },
    );
    let _ = String::from_utf8(text).expect("valid UTF-8 output");

    // extensions: field 2, level 0, declared type TestMessageSet.
    let extensions = spans
        .iter()
        .find(|s| s.field_number == 2 && s.level == 0)
        .expect("extensions span");
    assert_eq!(
        extensions.type_fqdn.as_deref(),
        Some("test_ms.TestMessageSet")
    );

    // Two Item wrappers (virtual: field_number 0, type_fqdn None), one per
    // resolved extension, each nested one level inside `extensions`.
    let items: Vec<&NodeSpan> = spans
        .iter()
        .filter(|s| s.field_number == 0 && s.level == 1 && s.type_fqdn.is_none())
        .collect();
    assert_eq!(items.len(), 2, "expected 2 Item wrappers");
    for item in &items {
        assert_contains("extensions", &extensions.raw_range, "Item", &item.raw_range);
        assert_contains(
            "extensions",
            &extensions.text_range,
            "Item",
            &item.text_range,
        );
    }

    // message {} wrapper for ExtPayloadA — resolved type, one level deeper
    // than its enclosing Item.
    let msg_a = spans
        .iter()
        .find(|s| {
            s.field_number == 0
                && s.level == 2
                && s.type_fqdn.as_deref() == Some("test_ms.ExtPayloadA")
        })
        .expect("message{} wrapper for ExtPayloadA");
    let item_a = items
        .iter()
        .find(|i| contains(&i.raw_range, &msg_a.raw_range))
        .expect("enclosing Item for ExtPayloadA's message{} wrapper");
    assert_contains("Item", &item_a.raw_range, "message", &msg_a.raw_range);
    assert_contains("Item", &item_a.text_range, "message", &msg_a.text_range);

    // ExtPayloadA's own scalar fields (label=1, value=2), one level deeper
    // than message{} — the 4th level of nesting.
    let msg_a_children: Vec<&NodeSpan> = spans
        .iter()
        .filter(|s| s.level == 3 && contains(&msg_a.raw_range, &s.raw_range))
        .collect();
    assert_eq!(
        msg_a_children.len(),
        2,
        "expected label+value under message{{}}"
    );
    for child in &msg_a_children {
        assert!(
            child.type_fqdn.is_none(),
            "scalar leaf must have type_fqdn: None"
        );
        assert_contains("message", &msg_a.raw_range, "scalar", &child.raw_range);
        assert_contains("message", &msg_a.text_range, "scalar", &child.text_range);
    }

    // name (sibling scalar to `extensions` at level 0) does not overlap
    // extensions's own range.
    let name = spans
        .iter()
        .find(|s| s.field_number == 1 && s.level == 0)
        .expect("name span");
    assert!(
        name.raw_range.end <= extensions.raw_range.start
            || extensions.raw_range.end <= name.raw_range.start,
        "sibling 'name' and 'extensions' raw_ranges must not overlap"
    );
}

// ── Line-number survival across the group-splice path ──────────────────────

#[test]
fn line_number_survival_across_group_splice() {
    let schema = knife_schema("SwissArmyKnife");

    // GROUP field 13 (tag byte 0x6b = (13 << 3) | WT_START_GROUP), containing
    // one undeclared varint field 1 = 42 (tag 0x08, value 0x2a), with no
    // END_GROUP — buffer runs out mid-group (open-ended group), forcing
    // `render_group_field`'s post-hoc "OPEN_GROUP" splice (Design rationale,
    // spec 0110).
    let wire: &[u8] = &[0x6b, 0x08, 0x2a];
    let (text, spans) = decode_and_render_indexed(
        wire,
        schema.root_descriptor().as_ref(),
        DecodeRenderOpts {
            annotations: true,
            emit_header: true,
            ..Default::default()
        },
    );
    let text = String::from_utf8(text).expect("valid UTF-8 output");

    let group = spans
        .iter()
        .find(|s| s.field_number == 13 && s.level == 0)
        .expect("group span");
    let child = spans
        .iter()
        .find(|s| s.field_number == 1 && s.level == 1)
        .expect("child scalar span inside group");

    assert_contains("group", &group.text_range, "child", &child.text_range);
    assert_contains("group", &group.raw_range, "child", &child.raw_range);

    // The splice inserts "; OPEN_GROUP" into the group's own opening line
    // (the line at `group.text_range.start`), before it ever writes the
    // child's or the closing "}" line.
    let open_line = line_at(&text, group.text_range.start);
    assert!(
        open_line.contains("OPEN_GROUP"),
        "expected OPEN_GROUP annotation on group's opening line: {open_line:?}\nfull text:\n{text}"
    );

    // The child's own line, recorded (as a line *number*) before the splice
    // ran, still points at the correct content afterward.
    let child_line = line_at(&text, child.text_range.start);
    assert!(
        child_line.contains("42"),
        "expected child scalar value 42 on its recorded line: {child_line:?}\nfull text:\n{text}"
    );
}

// ── Any expansion ────────────────────────────────────────────────────────

#[test]
fn any_expansion_value_wrapper_gets_resolved_type() {
    let schema = any_schema();
    let wire = any_wire_bytes();

    let (text, spans) = with_any_loader(&schema, || {
        decode_and_render_indexed(
            &wire,
            schema.root_descriptor().as_ref(),
            DecodeRenderOpts {
                annotations: true,
                emit_header: true,
                ..Default::default()
            },
        )
    });
    let _ = String::from_utf8(text).expect("valid UTF-8 output");

    // Container.payload: field 1, level 0, declared type google.protobuf.Any.
    let payload = spans
        .iter()
        .find(|s| s.field_number == 1 && s.level == 0)
        .expect("payload span");
    assert_eq!(payload.type_fqdn.as_deref(), Some("google.protobuf.Any"));

    // value {} wrapper: virtual (field_number 0), one level deeper, resolved
    // to acme.Payload — distinct from both the container's own declared type
    // and (trivially) from its scalar children's type_fqdn.
    let value = spans
        .iter()
        .find(|s| s.field_number == 0 && s.level == 1)
        .expect("value{} wrapper span");
    assert_eq!(value.type_fqdn.as_deref(), Some("acme.Payload"));
    assert_ne!(value.type_fqdn, payload.type_fqdn);
    assert_contains("payload", &payload.raw_range, "value", &value.raw_range);
    assert_contains("payload", &payload.text_range, "value", &value.text_range);

    let label = spans
        .iter()
        .find(|s| s.field_number == 1 && s.level == 2)
        .expect("label span");
    assert!(label.type_fqdn.is_none());
    assert_ne!(label.type_fqdn, value.type_fqdn);
    assert_contains("value", &value.raw_range, "label", &label.raw_range);
    assert_contains("value", &value.text_range, "label", &label.text_range);
}

// ── MessageSet expansion ───────────────────────────────────────────────────

#[test]
fn message_set_expansion_wrapper_nodes_get_resolved_type() {
    let schema = message_set_schema("Container");
    let (text, spans) = decode_and_render_indexed(
        CONTAINER_WIRE,
        schema.root_descriptor().as_ref(),
        DecodeRenderOpts {
            annotations: true,
            emit_header: true,
            ..Default::default()
        },
    );
    let _ = String::from_utf8(text).expect("valid UTF-8 output");

    let extensions = spans
        .iter()
        .find(|s| s.field_number == 2 && s.level == 0)
        .expect("extensions span");

    // Item {} wrapper: virtual, no type of its own (spec 0110 §3).
    let item = spans
        .iter()
        .find(|s| s.field_number == 0 && s.level == 1 && s.type_fqdn.is_none())
        .expect("Item{} wrapper span");
    assert_contains("extensions", &extensions.raw_range, "Item", &item.raw_range);

    // message {} wrapper for ExtPayloadA: virtual, resolved type — distinct
    // from the enclosing MessageSet's own declared type and from its
    // scalar children's (absent) type_fqdn.
    let msg_a = spans
        .iter()
        .find(|s| {
            s.field_number == 0
                && s.level == 2
                && s.type_fqdn.as_deref() == Some("test_ms.ExtPayloadA")
        })
        .expect("message{} wrapper for ExtPayloadA");
    assert_ne!(msg_a.type_fqdn, extensions.type_fqdn);
    assert_contains(
        "extensions",
        &extensions.raw_range,
        "message",
        &msg_a.raw_range,
    );
    assert_contains(
        "extensions",
        &extensions.text_range,
        "message",
        &msg_a.text_range,
    );

    let label = spans
        .iter()
        .find(|s| s.level == 3 && contains(&msg_a.raw_range, &s.raw_range) && s.field_number == 1)
        .expect("ExtPayloadA.label span");
    assert!(label.type_fqdn.is_none());
    assert_ne!(label.type_fqdn, msg_a.type_fqdn);
    assert_contains("message", &msg_a.raw_range, "label", &label.raw_range);
}

// ── Scalar leaf nodes ───────────────────────────────────────────────────────

#[test]
fn scalar_leaf_nodes_have_no_type_fqdn() {
    let schema = message_set_schema("Container");
    let (_text, spans) = decode_and_render_indexed(
        CONTAINER_WIRE,
        schema.root_descriptor().as_ref(),
        DecodeRenderOpts {
            annotations: true,
            emit_header: true,
            ..Default::default()
        },
    );

    // `name` (top-level scalar) and every scalar 3 levels deep (label,
    // value, flag, count) must all have type_fqdn: None.
    let scalar_leaves: Vec<&NodeSpan> = spans
        .iter()
        .filter(|s| s.level == 0 && s.field_number == 1) // name
        .chain(spans.iter().filter(|s| s.level == 3)) // label/value/flag/count
        .collect();
    assert!(
        !scalar_leaves.is_empty(),
        "expected at least one scalar leaf span"
    );
    for leaf in scalar_leaves {
        assert!(
            leaf.type_fqdn.is_none(),
            "scalar leaf (field {}) must have type_fqdn: None, got {:?}",
            leaf.field_number,
            leaf.type_fqdn
        );
    }
}

// ── Packed-repeated scalar fields (spec 0115) ───────────────────────────────

#[test]
fn packed_repeated_field_gets_one_node_span_per_element() {
    use prost::Message as _;
    use prost_reflect::DescriptorPool;
    use prost_types::field_descriptor_proto::{Label, Type};
    use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorProto};

    let msg_desc = DescriptorProto {
        name: Some("Msg".to_string()),
        field: vec![FieldDescriptorProto {
            name: Some("vals".to_string()),
            number: Some(1),
            label: Some(Label::Repeated as i32),
            r#type: Some(Type::Int32 as i32),
            ..Default::default()
        }],
        ..Default::default()
    };
    let file = FileDescriptorProto {
        name: Some("test_node_span_packed.proto".to_string()),
        package: Some("test".to_string()),
        message_type: vec![msg_desc],
        syntax: Some("proto3".to_string()),
        ..Default::default()
    };
    let mut file_bytes = Vec::new();
    file.encode(&mut file_bytes).unwrap();
    let mut pool = DescriptorPool::new();
    pool.decode_file_descriptor_proto(file_bytes.as_slice())
        .expect("cannot add test proto to pool");
    let schema = schema_from_pool(pool, "test.Msg").expect("cannot build schema");

    // vals: field 1 (LEN, packed by default in proto3), tag (1<<3)|2 =
    // 0x0a, len 3, payload [0x01, 0x02, 0x03] (three varint elements).
    let wire: &[u8] = &[0x0a, 0x03, 0x01, 0x02, 0x03];

    let (_text, spans) = decode_and_render_indexed(
        wire,
        schema.root_descriptor().as_ref(),
        DecodeRenderOpts {
            annotations: true,
            emit_header: true,
            ..Default::default()
        },
    );

    let elems: Vec<&NodeSpan> = spans.iter().filter(|s| s.field_number == 1).collect();
    assert_eq!(elems.len(), 3, "expected one NodeSpan per packed element");
    for (i, elem) in elems.iter().enumerate() {
        assert!(!elem.is_message);
        assert_eq!(
            elem.packed_record_start,
            Some(0),
            "packed_record_start must point at the record's own tag"
        );
        // Element i's own byte, at offset 2 (tag+length) + i.
        assert_eq!(elem.raw_range, (2 + i)..(2 + i + 1));
        // Line i+1: line 0 is the `#@ prototext...` header (emit_header:
        // true).
        assert_eq!(elem.text_range, (i + 1)..(i + 2));
    }
}

#[test]
fn empty_packed_repeated_field_keeps_a_single_whole_record_span() {
    use prost::Message as _;
    use prost_reflect::DescriptorPool;
    use prost_types::field_descriptor_proto::{Label, Type};
    use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorProto};

    let msg_desc = DescriptorProto {
        name: Some("Msg".to_string()),
        field: vec![FieldDescriptorProto {
            name: Some("vals".to_string()),
            number: Some(1),
            label: Some(Label::Repeated as i32),
            r#type: Some(Type::Int32 as i32),
            ..Default::default()
        }],
        ..Default::default()
    };
    let file = FileDescriptorProto {
        name: Some("test_node_span_packed_empty.proto".to_string()),
        package: Some("test".to_string()),
        message_type: vec![msg_desc],
        syntax: Some("proto3".to_string()),
        ..Default::default()
    };
    let mut file_bytes = Vec::new();
    file.encode(&mut file_bytes).unwrap();
    let mut pool = DescriptorPool::new();
    pool.decode_file_descriptor_proto(file_bytes.as_slice())
        .expect("cannot add test proto to pool");
    let schema = schema_from_pool(pool, "test.Msg").expect("cannot build schema");

    // vals: field 1 (LEN, packed), tag 0x0a, len 0, no payload.
    let wire: &[u8] = &[0x0a, 0x00];

    let (_text, spans) = decode_and_render_indexed(
        wire,
        schema.root_descriptor().as_ref(),
        DecodeRenderOpts {
            annotations: true,
            emit_header: true,
            ..Default::default()
        },
    );

    let elems: Vec<&NodeSpan> = spans.iter().filter(|s| s.field_number == 1).collect();
    assert_eq!(
        elems.len(),
        1,
        "an empty packed record falls back to one whole-record span"
    );
    assert_eq!(elems[0].raw_range, 0..2);
    assert!(elems[0].packed_record_start.is_none());
}

// ── `raw_range` fidelity ────────────────────────────────────────────────────

#[test]
fn raw_range_fidelity_reslices_and_redecodes() {
    let schema = any_schema();
    let wire = any_wire_bytes();

    let (_text, spans) = with_any_loader(&schema, || {
        decode_and_render_indexed(
            &wire,
            schema.root_descriptor().as_ref(),
            DecodeRenderOpts {
                annotations: true,
                emit_header: true,
                ..Default::default()
            },
        )
    });

    // A nested (not top-level) node: the Any's `value {}` wrapper, resolved
    // to acme.Payload.
    let value = spans
        .iter()
        .find(|s| s.field_number == 0 && s.level == 1)
        .expect("value{} wrapper span");
    assert_eq!(value.type_fqdn.as_deref(), Some("acme.Payload"));

    // Slice `value`'s raw_range directly from the original top-level buf —
    // absolute, no re-slicing through ancestors needed — and independently
    // re-decode it under its own resolved type.
    let sub_slice = &wire[value.raw_range.clone()];

    let payload_schema =
        schema_from_pool(schema.pool().clone(), "acme.Payload").expect("payload schema");
    let redecoded = prototext_core::render_as_text(
        sub_slice,
        payload_schema.root_descriptor().as_ref(),
        prototext_core::RenderOpts {
            assume_binary: true,
            include_annotations: false,
            indent: 1,
            expand_any: true,
            hide_unknown_fields: false,
            expand_message_set: true,
        },
    )
    .expect("re-decode sliced raw_range");
    let redecoded = String::from_utf8(redecoded).unwrap();
    assert!(
        redecoded.contains("hello"),
        "expected re-decoded raw_range slice to contain label 'hello': {redecoded}"
    );
}
