# SPDX-FileCopyrightText: 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
#
# SPDX-License-Identifier: MIT

[package]
name        = "prototext-schema"
version.workspace    = true
edition     = "2021"
description = "On-demand FileDescriptorProto loading from a mmapped descriptor set and its rkyv index"
license     = "MIT"
repository.workspace = true

[lib]
name       = "prototext_schema"
crate-type = ["rlib"]

[dependencies]
prototext-graph = { workspace = true }
memmap2         = "0.9"
rkyv            = { version = "0.8", features = ["little_endian"] }
prost           = "0.14"
prost-reflect   = "0.16"
prost-types     = "0.14"
workspace-hack  = { version = "0.1", path = "../workspace-hack" }
