# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "SchemaHandle",
    "format_as_bytes",
    "format_as_text",
    "register_schema",
]

@typing.final
class SchemaHandle:
    r"""
    Opaque handle to a parsed protobuf schema.
    
    Created once per unique schema via `register_schema()`.
    Lifetime managed by Python reference counting.
    """
    ...

def format_as_bytes(data: bytes, assume_binary: builtins.bool = False) -> bytes:
    r"""
    Decode a protobuf payload and return it as raw binary wire bytes.
    
    Parameters
    ----------
    data : bytes
        The input payload.  Interpretation depends on ``assume_binary``.
    assume_binary : bool, optional
        When ``True``, ``data`` is already a raw protobuf binary wire payload
        and is returned unchanged (passthrough — prototext is bit-level
        faithful and never normalises the wire encoding).
        When ``False`` (default), the format is auto-detected:
    
      * If `data` starts with `b"#@ prototext:"` it is textual prototext
        produced by `format_as_text`; it is decoded line-by-line and
        re-encoded directly to binary wire bytes.
      * Otherwise `data` is returned unchanged.
    
    Returns
    -------
    bytes
        Raw protobuf binary wire bytes.
    """

def format_as_text(data: bytes, schema: typing.Optional[SchemaHandle] = None, assume_binary: builtins.bool = False, include_annotations: builtins.bool = False, indent: builtins.int = 1) -> bytes:
    r"""
    Decode a protobuf payload and render it as protoc-style text.
    
    Parameters
    ----------
    data : bytes
        The input payload.  When ``assume_binary`` is ``False`` (default) the
        function auto-detects the format: if the payload starts with the
        ``#@ prototext:`` magic header it is already textual and returned
        unchanged (zero-copy fast path).  Otherwise it is treated as raw
        protobuf binary and decoded+rendered in a single pass.
        When ``assume_binary=True`` the auto-detection step is skipped and the
        payload is always decoded as raw protobuf binary.
    schema : SchemaHandle, optional
        Schema handle from `register_schema()`.
    assume_binary : bool, optional
        Skip format auto-detection and treat ``data`` as raw protobuf binary.
        Default ``False``.
    include_annotations : bool, optional
        Emit inline comments with schema field names and types.  Default
        ``False``.
    indent : int, optional
        Indentation step in spaces used by the protoc text renderer.
        Default ``1``.
    
    Returns
    -------
    bytes
        Protoc-style text representation of the decoded message, encoded as
        UTF-8 bytes.  The fast path returns the original ``data`` object
        unchanged (zero copy).
    """

def register_schema(schema_data: bytes, root_message: builtins.str) -> SchemaHandle:
    r"""
    Parse and register a protobuf schema for use with `format_as_text()`.
    
    Parameters
    ----------
    schema_data : bytes
        A serialised ``FileDescriptorProto`` or ``FileDescriptorSet``, in
        either raw binary wire format **or** textual prototext format (i.e.
        starting with ``b"#@ prototext:"``, as produced by
        ``format_as_text()``).  The format is auto-detected and normalised to
        binary before the schema is parsed.
        Pass ``b""`` together with ``root_message=""`` to create a no-schema
        handle (all fields decoded as generic wire types).
    root_message : str
        Fully-qualified message name, e.g. ``"my.package.MyMessage"``.
        The leading dot is optional.
    
    Returns
    -------
    SchemaHandle
        Opaque handle; pass to `format_as_text()`.
    """

