// SPDX-FileCopyrightText: 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
//
// SPDX-License-Identifier: MIT

//! The `F1` help overlay's text.
//!
//! Its own file because it is prose, not code: 180 lines of it with no
//! logic to read it against, which used to sit between the enums above
//! it and the `App` struct below. `tests/help_text.rs` is what keeps it
//! honest.

/// Static key-binding reference shown by the `F1` help overlay (spec 0111
/// Annex C, spec 0113 D22) — kept as one flat text block rather than
/// generated from the `handle_key` match arms, so it can be phrased for
/// readability independent of the code's own binding order.
pub(super) const HELP_TEXT: &[&str] = &[
    "protolens — key bindings",
    "",
    "Movement — the text first, then on past its edges into the tree",
    "  h / Left / Backspace / Ctrl-B",
    "                   caret one character left; at the first non-blank,",
    "                   fold this node, then move to its parent",
    "  l / Right / Ctrl-F",
    "                   caret one character right; at the first non-blank",
    "                   of a folded node, unfold it; at the last",
    "                   reachable column, move to the first child",
    "  Alt-Left / Alt-h / Alt-B",
    "                   caret one word left",
    "  Alt-Right / Alt-l / Alt-F",
    "                   caret one word right",
    "  ^ / Ctrl-A       caret to first non-blank",
    "  click in the left margin",
    "                   the same, for the line clicked — the margin does",
    "                   not pan, so it means this however far the view",
    "                   has scrolled sideways",
    "  $ / Ctrl-E       caret to last reachable column",
    "  %                jump between the cursor node's { and }",
    "  j / Down / Ctrl-N  next node (document order)",
    "  k / Up / Ctrl-P  previous node",
    "  Ctrl-j / Ctrl-Down  next sibling",
    "  Ctrl-k / Ctrl-Up    previous sibling",
    "  Home / gg        jump to first node",
    "  End / G          jump to last visible node",
    "  Space / f / PageDown",
    "                   scroll down one page",
    "  Shift-Space / b / PageUp",
    "                   scroll up one page — Shift-Space needs terminal",
    "                   support for modifier reporting, b always works",
    "  Shift-Alt-Up     pan main pane left",
    "  Shift-Alt-Down   pan main pane right",
    "  Alt-Up           pan main pane up, cursor stays in view",
    "  Alt-Down         pan main pane down, cursor stays in view",
    "  Shift+wheel / native horizontal scroll",
    "                   pan whichever pane (main, override, manage, or",
    "                   the command bar) the mouse is hovering",
    "",
    "Selection",
    "  H / Shift-Left   extend the selection one character left",
    "  L / Shift-Right  extend it one character right",
    "  K / Shift-Up     extend it one row up",
    "  J / Shift-Down   extend it one row down",
    "                   the first of these anchors where the caret is,",
    "                   so Shift-Right Shift-Left selects one character;",
    "                   any other key drops the selection, as does Esc",
    "  drag (main pane) the same selection, made with the mouse — the",
    "                   drag moves the caret and the anchor stays where",
    "                   the click landed, so dragging off a character and",
    "                   back selects just it; a plain click selects",
    "                   nothing, and a double-click folds instead",
    "  Ctrl-click       extend the selection to the clicked character,",
    "  / Shift-click    anchoring at the caret if nothing is selected",
    "                   yet; use Ctrl-click if your terminal keeps",
    "                   Shift-click for its own native selection",
    "  Ctrl-C           copy the selection to the OS clipboard, or the",
    "                   cursor's whole line when nothing is selected —",
    "                   a selection spanning a folded node copies what it",
    "                   hides, not the { ... } placeholder",
    "",
    "Fold / unfold",
    "  z                toggle fold on the node under the cursor",
    "  Z                the same, and force every descendant into the",
    "                   state the node itself just took",
    "  0 .. 9           open the node under the cursor to that depth and",
    "                   fold everything below it: 0 closes it entirely,",
    "                   1 opens it with its children folded, 2 opens one",
    "                   level more, and so on. The digit is the depth, so",
    "                   pressing it twice changes nothing",
    "  Ctrl-h / Ctrl-Left   fold all siblings at this level",
    "  Ctrl-l / Ctrl-Right  unfold all siblings at this level",
    "  click on a fold marker",
    "                   toggle that node and put the cursor on it",
    "  double-click on a row",
    "                   the same as z, on the node that row belongs to —",
    "                   anywhere in its text, so the margin is not the",
    "                   only way in from the mouse. A double-click that",
    "                   turns into a drag selects instead, and folds",
    "                   nothing",
    "",
    "Display",
    "  a                toggle main-pane #@ annotation display",
    "  w                show the bytes, in hex, under the caret's own",
    "                   line — or under every selected line — in a second",
    "                   row beneath each; again on a line already showing",
    "                   them puts them away",
    "  W                the same for the whole subtree the caret is in",
    "  Ctrl-w           put the bytes away, wherever they are — w and W",
    "                   only turn a run off from a row inside it",
    "  (resting the pointer on a document row's field key, value, #@",
    "   marker or any part of the annotation after it says what that",
    "   token means — a little longer than the boxes below, since an",
    "   explanation is asked for rather than travelled over)",
    "  (resting the pointer on a wire row's wire type, field number,",
    "   length or value says what those bytes are — and on its ?? or",
    "   its elision mark, says what is not there; over a value, the",
    "   glyphs that one byte spells light up in the reading)",
    "",
    "Heat cues",
    "  i / I            rotate through three views, forward / back:",
    "                   nothing; then the findings — a dot in the left",
    "                   margin and a [current/best] suffix, on a node",
    "                   whose bytes fit some other type better than the",
    "                   one it has; then every scored node, where a node",
    "                   that is the best fit says its own [score] in",
    "                   green and one nothing fits says [vetoed]",
    "  s                what that score is made of, for the node under",
    "                   the cursor — one line per category the scorer",
    "                   counted, with its weight",
    "  (resting the pointer on a type name in a #@ annotation shows the",
    "   same box for that line; anything else at all dismisses it)",
    "  double-click on a [ ] cue",
    "                   open the override selection pane for that node,",
    "                   same as t — the cue asks the question, the pane",
    "                   is the answer",
    "",
    "Navigation history",
    "  Ctrl-O           jump back",
    "  Ctrl-I           jump forward",
    "",
    "Export",
    "  x                arm the export chord — xb/xp pre-fill \":export\"",
    "                   for binary/prototext data; xd arms a second",
    "                   chord — xdb/xdp pre-fill \":export\" for binary/",
    "                   prototext schema",
    "  :export [--binary|--prototext|--descriptor-binary|",
    "           --descriptor-prototext] <path>",
    "                   export the cursor node to <path> — default",
    "                   format is #@ prototext text; --descriptor-binary/",
    "                   --descriptor-prototext export a synthetic schema",
    "                   for the cursor's live-tree children instead of",
    "                   its data",
    "",
    "Command line",
    "  :                open the command line — works from any pane, so",
    "                   every command below is reachable without first",
    "                   returning focus to the main pane",
    "  Tab              complete the command name (longest common prefix,",
    "                   then cycle through matches)",
    "  Shift-Tab        cycle backward through matches",
    "  Ctrl-B / Ctrl-F  caret one character left / right",
    "  Alt-B / Alt-F    caret one word left / right",
    "  Left / Right     caret one character left / right",
    "  Alt-Left / Alt-Right  caret one word left / right",
    "  Ctrl-V           paste the OS clipboard at the caret — the command",
    "                   line is one line, so only the clipboard's first",
    "                   line is inserted",
    "  Esc              discard the command line",
    "  :quit            quit — the only way out (:q is enough, no other",
    "                   command starts with q)",
    "  :help            open this help",
    "  :proto-root <dir>",
    "                   set the root the v key resolves .proto sources",
    "                   against, overriding --proto-root for this session",
    "",
    "Search (main pane, requires main-pane focus)",
    "  /                search forward for a pattern (matches against the",
    "                   current, possibly-overridden rendering)",
    "  ?                search backward",
    "  n                repeat the last search, same direction",
    "  N                repeat the last search, opposite direction",
    "  F                find forward: like / but pre-filled with the last",
    "                   pattern, and the prompt stays open — Enter steps to",
    "                   the next match, Esc accepts and puts the caret on",
    "                   the match's first character",
    "  B                the same, backward",
    "  (in a find prompt Shift-Right steps in the direction F/B named and",
    "   Shift-Left the opposite way, while Ctrl-Right/Ctrl-Left step",
    "   forward/backward through the document; each of them also aims the",
    "   next Enter, and the >/< prefix says where that points)",
    "  (a hit puts the caret on the match itself)",
    "  (at any search prompt Up/Down browse the pattern history, and",
    "   Ctrl-P/Ctrl-N are the same two keys)",
    "  (confirming / or ? with no typed pattern reuses the last one)",
    "  (a pattern is also matched against each node's positional path,",
    "   anchored at the path's start — so /2/1 finds that node, and a",
    "   pattern not starting with / searches the text only)",
    "",
    "Override pane",
    "  t                open the override pane for the message/group",
    "                   node under the cursor",
    "  Tab              move focus between the main pane and the",
    "                   override pane (while it is open)",
    "  i                toggle candidate sort: inferred score (default)",
    "                   or alphanumeric",
    "  /  ?  n  N       search / search backward / repeat / repeat",
    "                   opposite direction (pane focused)",
    "  F  B             find forward / backward: a prompt that stays open",
    "                   and steps through the matches (pane focused)",
    "  j/k or Ctrl-N/Ctrl-P, PageUp/Down, Home/End",
    "                   move the highlighted candidate",
    "                   (pane focused)",
    "  Ctrl-Left/Ctrl-Right         pan the pane horizontally",
    "  Ctrl-Up/Ctrl-Down            pan the pane vertically, highlight",
    "                   stays in view",
    "  Alt-Up/Alt-Down  the same vertical pan, a second spelling",
    "  Enter            apply the highlighted type (pane focused) and",
    "                   close the pane; also records the override in the",
    "                   collection (see \"Override management\" below)",
    "  o                edit the target node's override — origin, type",
    "                   and display name at once — as a pre-filled",
    "                   \":override\"",
    "  z  Z             rotate the origin kind the statusline projects —",
    "                   fqdn-field, path-field, path — away from the",
    "                   widest one this node can express (Z reverses)",
    "  Esc              cancel and close the override pane — the only way",
    "                   out of it",
    "",
    "Override management",
    "  o                open/close the override management pane (closes",
    "                   the override pane, if open)",
    "  Enter            close the management pane",
    "  Tab              move focus between the main pane and the",
    "                   management pane (while it is open)",
    "  j/k or Ctrl-N/Ctrl-P, PageUp/Down, Home/End",
    "                   move the highlighted entry",
    "  Shift-Up / Shift-Down        move the highlighted entry and",
    "                   activate the destination (deactivating any",
    "                   other entry sharing its origin)",
    "  Left/Right       move the main-pane cursor to the prev/next field",
    "                   affected by the highlighted entry (wraps around)",
    "  Ctrl-Left/Ctrl-Right         pan the pane horizontally",
    "  Ctrl-Up/Ctrl-Down            pan the pane vertically, highlight",
    "                   stays in view",
    "  /  ?  n  N       search / search backward / repeat / repeat",
    "                   opposite direction",
    "  F  B             find forward / backward: a prompt that stays open",
    "                   and steps through the matches",
    "  a / Space        toggle the highlighted entry active/inactive",
    "  A / Shift-Space  same, but also cascades the new state to every",
    "                   entry whose origin sits at-or-under it (a",
    "                   descendant path, or a path-field/fqdn-field at",
    "                   the same path); when several entries would",
    "                   activate under one origin, only the first",
    "                   (sorted) one does — Shift-Space needs terminal",
    "                   support (Kitty keyboard protocol); also",
    "                   available as Shift-click or double-click on an",
    "                   entry's marker",
    "  z / Z            rotate the highlighted entry's origin kind",
    "                   forward/backward: path, path-field, fqdn-field;",
    "                   auto-resolves from the fields the entry affects,",
    "                   falling back to the main-pane cursor/message line",
    "                   when ambiguous; repeating z/Z with the cursor",
    "                   unchanged advances to the next kind instead of",
    "                   getting stuck",
    "  d / Delete / Backspace  remove the highlighted entry from the",
    "                   collection (an auto-derived entry still in scope",
    "                   is deactivated instead, since deleting it would",
    "                   just recreate it)",
    "  D                duplicate the highlighted entry (the copy starts",
    "                   inactive and is always manual, even if the",
    "                   original was auto-derived)",
    "  o                edit the highlighted entry — origin, type and",
    "                   display name at once — as a pre-filled",
    "                   \":override\" (pane focused)",
    "  Esc              close the management pane",
    "  :override <origin> [--as <FQDN>] [--field-name <name>]",
    "                   record an override: render <origin> as <FQDN>,",
    "                   or as raw/unschema'd when --as is omitted, and",
    "                   name the field <name> in its parent. <origin> is",
    "                   required, and is /path, /path:field or",
    "                   fqdn:field. Tab rotates <origin> through those",
    "                   three shapes and --field-name through the four",
    "                   ways of naming a field (entry name, schema name,",
    "                   f<field-number>, p<position>); Tab on --as",
    "                   completes inferred types by score, falling back",
    "                   to the alphabetic list; Tab after a leading -",
    "                   completes the options",
    "  entry rows: auto-derived entries are plain, manual entries bold",
    "  s                pre-fill \":save-overrides <default path>\"",
    "  r                pre-fill \":restore-overrides \"",
    "  :save-overrides <path>",
    "                   write the whole override collection to <path>",
    "                   as YAML",
    "  :restore-overrides <path>",
    "                   replace the override collection wholesale with",
    "                   <path>'s contents (entries that no longer",
    "                   resolve are silently dropped; a target-hash",
    "                   mismatch warns but does not block)",
    "  Tab              complete a filesystem path (save/restore",
    "                   argument)",
    "  (management-pane actions never change the current rendering —",
    "  only Enter in the override pane does)",
    "",
    "Script (only when a .script file was loaded — see --script)",
    "  Space            turn script navigation on or off; turning it on",
    "                   also puts the view back where the current step",
    "                   left it, so wandering off between steps is free",
    "  ;                next step        (navigation on)",
    "  ,                previous step    (navigation on)",
    "  .                scroll the script pane down  (navigation on)",
    "  ?                scroll the script pane up    (navigation on)",
    "                   these four work whichever pane has focus; with",
    "                   navigation off they are the bindings they always",
    "                   were — note that ? is backward search, and is the",
    "                   only one of the four the script takes from you",
    "  (the arrow keys are never the script's: a presenter reaches for one",
    "   by reflex, and a reflex must not change step)",
    "  (a step that pre-fills the command line leaves the Enter to you)",
    "",
    "Context menu",
    "  right-click      open a menu of the actions that apply to what you",
    "                   clicked — in the main pane, the node under the",
    "                   pointer (the caret moves there first); in the",
    "                   management pane, the entry under it; past the end",
    "                   of the document, the view's own settings, since",
    "                   there is no node there to act on",
    "  m / Menu         the same menu, at the caret instead of the",
    "                   pointer — use it if your terminal keeps the right",
    "                   button for a menu of its own (GNOME Console and",
    "                   the other VTE terminals do; Alacritty has none)",
    "  j / k / Down / Up / Ctrl-N / Ctrl-P",
    "                   move the highlight",
    "  Home / End       first / last row",
    "  Enter            run the highlighted row",
    "  Esc / click away close the menu, having done nothing",
    "  (every row is one of the bindings documented above, and says so",
    "   on its right; that key works while the menu is open, so nothing",
    "   is reachable by menu alone)",
    "",
    "Other",
    "  v                open the FQDN under focus's .proto declaration in",
    "                   Neovim — works from any pane; needs a proto root",
    "                   (--proto-root or :proto-root) — Unix only",
    "  F1 / :help       open this help",
    "  Ctrl-Z           suspend (fg to resume) — Unix only",
    "",
    "This help is a pane like any other. j/k, Ctrl-N/Ctrl-P, f/b,",
    "PageUp/PageDown, Home and End/G move its cursor; Ctrl-Up/Ctrl-Down",
    "and Ctrl-Left/Ctrl-Right pan it without moving the cursor; /, ?, n,",
    "N, F and B search it. Esc or F1 closes it.",
];
