# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: f24_packed_wire_test.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'f24_packed_wire_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66\x32\x34_packed_wire_test.proto\x12\x06mockup\"^\n\x0ePackedWireTest\x12\x15\n\rdefault_field\x18\x01 \x03(\x05\x12\x19\n\rexplicit_true\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x1a\n\x0e\x65xplicit_false\x18\x03 \x03(\x05\x42\x02\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'f24_packed_wire_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKEDWIRETEST'].fields_by_name['explicit_true']._loaded_options = None
  _globals['_PACKEDWIRETEST'].fields_by_name['explicit_true']._serialized_options = b'\020\001'
  _globals['_PACKEDWIRETEST'].fields_by_name['explicit_false']._loaded_options = None
  _globals['_PACKEDWIRETEST'].fields_by_name['explicit_false']._serialized_options = b'\020\000'
  _globals['_PACKEDWIRETEST']._serialized_start=38
  _globals['_PACKEDWIRETEST']._serialized_end=132
# @@protoc_insertion_point(module_scope)
