# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "build_fds_index",
    "build_graph",
]

def build_fds_index(type_to_file: typing.Mapping[builtins.str, builtins.str], file_to_span: typing.Mapping[builtins.str, tuple[builtins.int, builtins.int]], dep_graph: typing.Mapping[builtins.str, typing.Sequence[builtins.str]]) -> bytes:
    r"""
    Serialize an FdsIndex to rkyv bytes with the PTSGRAPH header (version 3).
    
    Parameters
    ----------
    type_to_file : dict[str, str]
        Fully-qualified type name (no leading dot) → proto file name.
    file_to_span : dict[str, tuple[int, int]]
        Proto file name → (start, end) byte offsets in the raw .pb file.
    dep_graph : dict[str, list[str]]
        Proto file name → list of direct import file names.
    
    Returns
    -------
    bytes
        Serialized ``index.rkyv`` content (PTSGRAPH header + rkyv payload).
    
    Raises
    ------
    RuntimeError
        If serialization fails.
    """

def build_graph(scoring_graphs: typing.Sequence[builtins.str], emit_yaml: builtins.bool = False, emit_initial_yaml: builtins.bool = False, on_progress: typing.Optional[typing.Any] = None) -> tuple[bytes, typing.Optional[builtins.str], typing.Optional[builtins.str]]:
    r"""
    Build a compiled (baked) scoring graph from in-memory YAML strings.
    
    Parameters
    ----------
    scoring_graphs : list[str]
        YAML content of each per-file scoring graph, as produced by
        ``reproto --emit-scoring-graphs``.  One entry per file; order does
        not matter.
    emit_yaml : bool, optional
        When True, also return the minimised (post-Hopcroft) compiled graph as
        a human-readable YAML string (spec 0059 §2 format).  Default False.
    emit_initial_yaml : bool, optional
        When True, also return the raw (pre-Hopcroft) compiled graph as a
        human-readable YAML string (spec 0059 §2 format).  Default False.
    
    Returns
    -------
    tuple[bytes, str | None, str | None]
        First element: serialised ``.rkyv`` content (the baked graph).
        Second element: minimised YAML when ``emit_yaml=True``, else ``None``.
        Third element: raw YAML when ``emit_initial_yaml=True``, else ``None``.
    
    Raises
    ------
    RuntimeError
        If any YAML string is malformed or the graph cannot be built.
    """

