# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "scan",
]

def scan(buffer: bytes) -> builtins.list[tuple[builtins.int, builtins.int]]:
    r"""
    Scan a binary buffer for FileDescriptorProto candidates.
    
    Returns a list of (start, end) byte offsets for each candidate found.
    """

