// SPDX-FileCopyrightText: 2025 - 2026 Frederic Ruget <fred@atlant.is> (GitHub: @douzebis)
// SPDX-FileCopyrightText: 2025 - 2026 THALES CLOUD SECURISE SAS
//
// SPDX-License-Identifier: MIT

//! Build script: produce `$OUT_DIR/*.pb` descriptor sets.
//!
//! Two modes selected by the `protox` Cargo feature (on by default):
//!
//! - **`protox` enabled** (default, crates.io): compile `.proto` schemas using
//!   the pure-Rust `protox` compiler — no system `protoc` required.
//! - **`protox` disabled** (Nix builds): copy pre-compiled `.pb` files from
//!   `fixtures/prebuilt/`, which are generated by the Nix `patchPhase` using
//!   `protoc` before `cargo build` runs.
//!
//! Files produced in both modes:
//!   - `descriptor.pb`     — FileDescriptorSet for google/protobuf/descriptor.proto
//!   - `knife.pb`          — FileDescriptorSet for fixtures/schemas/knife.proto
//!   - `enum_collision.pb` — FileDescriptorSet for fixtures/schemas/enum_collision.proto
//!
//! `descriptor.pb` is embedded into the binary at compile time via:
//!   `include_bytes!(concat!(env!("OUT_DIR"), "/descriptor.pb"))`
//!
//! `knife.pb` and `enum_collision.pb` are used by integration tests only.

#[cfg(feature = "protox")]
use prost::Message as _;

#[cfg(feature = "protox")]
fn compile(files: &[&str], includes: &[&str], out_dir: &str, out_name: &str) {
    let descriptor = protox::compile(files, includes)
        .unwrap_or_else(|e| panic!("failed to compile {files:?}: {e}"));
    let bytes = descriptor.encode_to_vec();
    std::fs::write(format!("{out_dir}/{out_name}"), bytes)
        .unwrap_or_else(|e| panic!("failed to write {out_name}: {e}"));
}

#[cfg(not(feature = "protox"))]
fn copy_prebuilt(out_dir: &str, manifest_dir: &str) {
    let prebuilt = std::path::Path::new(manifest_dir).join("fixtures/prebuilt");
    for name in &["descriptor.pb", "knife.pb", "enum_collision.pb"] {
        let src = prebuilt.join(name);
        let dst = std::path::Path::new(out_dir).join(name);
        std::fs::copy(&src, &dst).unwrap_or_else(|e| panic!("failed to copy {name}: {e}"));
    }
}

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");

    #[cfg(feature = "protox")]
    {
        let schemas_dir = format!("{manifest_dir}/fixtures/schemas");
        compile(
            &["google/protobuf/descriptor.proto"],
            &[""],
            &out_dir,
            "descriptor.pb",
        );
        compile(&["knife.proto"], &[&schemas_dir], &out_dir, "knife.pb");
        compile(
            &["enum_collision.proto"],
            &[&schemas_dir],
            &out_dir,
            "enum_collision.pb",
        );
    }

    #[cfg(not(feature = "protox"))]
    copy_prebuilt(&out_dir, &manifest_dir);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=fixtures/schemas/knife.proto");
    println!("cargo:rerun-if-changed=fixtures/schemas/enum_collision.proto");
}
